### ISSUE TITLE
Latest mu/mu4e update seems to break query fragments

### ISSUE THREAD

**Issue by joostkremers** [wavexx/mu4e-query-fragments.el#1]
Yesterday I pulled the latest updates for mu/mu4e and now the query plugins seem to have stopped working. My fragment list contains the following:

```
(setq mu4e-query-fragments-list
      '(("%junk" . "maildir:\"/Fastmail/Junk Mail\"")
        ("%hidden" . "flag:trashed OR %junk")))
```

and I have the following bookmark:

```
(setq mu4e-bookmarks '(("flag:unread AND NOT %hidden" "Unread messages" ?u)))
```

I regularly trash mail from mailing lists that I don't read, so they still have the unread flag. Before the update, this bookmark didn't show them, now, after pulling the latest updates for mu, it does.

**Comment by wavexx** [comment]
On Sat, Oct 28 2017, Joost Kremers wrote:
> Yesterday I pulled the latest updates for mu/mu4e and now the query
> plugins seem to have stopped working. My fragment list contains the
> following:

I believe there is some recent issue in mu/mu4e with quoting:

  https://github.com/djcb/mu/issues/1140

You can verify that even if you disable query-fragments, plain search is
still broken.

Try fetching mu at commit 509500a9d2b00873e0b4484c4956e58a2ef6d83c

**Comment by joostkremers** [comment]
Ah, thanks! I can confirm that if I search in mu4e for `flag:unread AND NOT flag:trashed`, I get trashed messages. From the command line, it works correctly. I'll close this issue then and keep an eye on https://github.com/djcb/mu/issues/1140.
